export const TYPOGRAPHY_DEFAULTS = {
  allowFontScaling: true,
  maxFontSizeMultiplier: 1.15,
  fontFamily: {
    regular: "Montserrat",
    italic: "Montserrat-Italic",
    thin: "Montserrat-Thin",
    thinItalic: "Montserrat-ThinItalic",
    extraLight: "Montserrat-ExtraLight",
    extraLightItalic: "Montserrat-ExtraLightItalic",
    light: "Montserrat-Light",
    lightItalic: "Montserrat-LightItalic",
    medium: "Montserrat-Medium",
    mediumItalic: "Montserrat-MediumItalic",
    semiBold: "Montserrat-SemiBold",
    semiBoldItalic: "Montserrat-SemiBoldItalic",
    bold: "Montserrat-Bold",
    boldItalic: "Montserrat-BoldItalic",
    extraBold: "Montserrat-ExtraBold",
    extraBoldItalic: "Montserrat-ExtraBoldItalic",
    black: "Montserrat-Black",
    blackItalic: "Montserrat-BlackItalic",
  },
  android: {
    includeFontPadding: false,
  },
};
