        {
          "Abra": {
            "Bangued": [
              "Agtangao",
              "Angad",
              "Bañacao",
              "Bangbangar",
              "Cabuloan",
              "Calaba",
              "Tablac",
              "Cosili West",
              "Cosili East",
              "Dangdangla",
              "Lingtan",
              "Lipcan",
              "Lubong",
              "Macarcarmay",
              "Maoay",
              "Macray",
              "Malita",
              "Palao",
              "Patucannay",
              "Sagap",
              "San Antonio",
              "Santa Rosa",
              "Sao-atan",
              "Sappaac",
              "Zone 2 Pob.",
              "Zone 3 Pob.",
              "Zone 4 Pob.",
              "Zone 5 Pob.",
              "Zone 6 Pob.",
              "Zone 7 Pob.",
              "Zone 1 Pob."
            ],
            "Boliney": [
              "Amti",
              "Bao-yan",
              "Danac East",
              "Dao-angan",
              "Dumagas",
              "Kilong-Olao",
              "Poblacion",
              "Danac West"
            ],
            "Bucay": [
              "Abang",
              "Bangbangcag",
              "Bangcagan",
              "Banglolao",
              "Bugbog",
              "Calao",
              "Dugong",
              "Labon",
              "Layugan",
              "Madalipay",
              "Pagala",
              "Palaquio",
              "Pakiling",
              "Patoc",
              "North Poblacion",
              "South Poblacion",
              "Quimloong",
              "Salnec",
              "San Miguel",
              "Siblong",
              "Tabiog"
            ],
            "Bucloc": [
              "Ducligan",
              "Labaan",
              "Lingey",
              "Lamao"
            ],
            "Daguioman": [
              "Ableg",
              "Cabaruyan",
              "Pikek",
              "Tui"
            ],
            "Danglas": [
              "Abaquid",
              "Cabaruan",
              "Caupasan",
              "Nagaparan",
              "Padangitan",
              "Pangal"
            ],
            "Dolores": [
              "Bayaan",
              "Cabaroan",
              "Calumbaya",
              "Cardona",
              "Isit",
              "Kimmalaba",
              "Libtec",
              "Lub-lubba",
              "Mudiit",
              "Namit-ingan",
              "Pacac",
              "Poblacion",
              "Salucag",
              "Talogtog",
              "Taping"
            ],
            "La Paz": [
              "Benben",
              "Bulbulala",
              "Buli",
              "Canan",
              "Liguis",
              "Malabbaga",
              "Mudeng",
              "Pidipid",
              "Poblacion",
              "San Gregorio",
              "Toon",
              "Udangan"
            ],
            "Lacub": [
              "Bacag",
              "Buneg",
              "Guinguinabang",
              "Lan-ag",
              "Pacoc",
              "Poblacion"
            ],
            "Lagangilang": [
              "Aguet",
              "Bacooc",
              "Balais",
              "Cayapa",
              "Dalaguisen",
              "Laang",
              "Lagben",
              "Laguiben",
              "Nagtipulan",
              "Nagtupacan",
              "Paganao",
              "Pawa",
              "Poblacion",
              "Presentar"
            ],
            "San Isidro": [
              "Tagodtod",
              "Taping",
              "Cabayogan",
              "Dalimag",
              "Langbaban",
              "Manayday",
              "Pantoc",
              "Poblacion",
              "Sabtan-olo",
              "San Marcial",
              "Tangbao"
            ],
            "Lagayan": [
              "Ba-i",
              "Collago",
              "Pang-ot",
              "Poblacion",
              "Pulot"
            ],
            "Langiden": [
              "Baac",
              "Dalayap",
              "Mabungtot",
              "Malapaao",
              "Poblacion",
              "Quillat"
            ],
            "Licuan-Baay": [
              "Bonglo",
              "Bulbulala",
              "Cawayan",
              "Domenglay",
              "Lenneng",
              "Mapisla",
              "Mogao",
              "Nalbuan",
              "Poblacion",
              "Subagan",
              "Tumalip"
            ],
            "Luba": [
              "Ampalioc",
              "Barit",
              "Gayaman",
              "Lul-luno",
              "Luzong",
              "Nagbukel-Tuquipa",
              "Poblacion",
              "Sabnangan"
            ],
            "Malibcong": [
              "Bayabas",
              "Binasaran",
              "Buanao",
              "Dulao",
              "Duldulao",
              "Gacab",
              "Lat-ey",
              "Mataragan",
              "Pacgued",
              "Taripan",
              "Umnap"
            ],
            "Manabo": [
              "Catacdegan Viejo",
              "Luzong",
              "Ayyeng",
              "San Jose Norte",
              "San Jose Sur",
              "San Juan Norte",
              "San Juan Sur",
              "San Ramon East",
              "San Ramon West",
              "Santo Tomas",
              "Catacdegan Nuevo"
            ],
            "Peñarrubia": [
              "Dumayco",
              "Lusuac",
              "Namarabar",
              "Patiao",
              "Malamsit",
              "Poblacion",
              "Riang",
              "Santa Rosa",
              "Tattawa"
            ],
            "Pidigan": [
              "Alinaya",
              "Arab",
              "Garreta",
              "Immuli",
              "Laskig",
              "Naguirayan",
              "Monggoc",
              "Pamutic",
              "Pangtud",
              "Poblacion East",
              "Poblacion West",
              "San Diego",
              "Sulbec",
              "Suyo",
              "Yuyeng"
            ],
            "Pilar": [
              "Bolbolo",
              "Brookside",
              "Ocup",
              "Dalit",
              "Dintan",
              "Gapang",
              "Kinabiti",
              "Maliplipit",
              "Nagcanasan",
              "Nanangduan",
              "Narnara",
              "Pang-ot",
              "Patad",
              "Poblacion",
              "San Juan East",
              "San Juan West",
              "South Balioag",
              "Tikitik"
            ],
            "Villavieja": [],
            "Sallapadan": [
              "Bazar",
              "Bilabila",
              "Gangal",
              "Maguyepyep",
              "Naguilian",
              "Saccaang",
              "Subusob",
              "Ud-udiao"
            ],
            "San Juan": [
              "Abualan",
              "Ba-ug",
              "Badas",
              "Cabcaborao",
              "Colabaoan",
              "Culiong",
              "Daoidao",
              "Guimba",
              "Lam-ag",
              "Lumobang",
              "Nangobongan",
              "Pattaoig",
              "Poblacion North",
              "Poblacion South",
              "Quidaoen",
              "Sabangan",
              "Silet",
              "Supi-il",
              "Tagaytay"
            ],
            "San Quintin": [
              "Labaan",
              "Palang",
              "Pantoc",
              "Poblacion",
              "Tangadan",
              "Villa Mercedes"
            ],
            "Tayum": [
              "Bagalay",
              "Basbasa",
              "Budac",
              "Bumagcat",
              "Cabaroan",
              "Deet",
              "Gaddani",
              "Patucannay",
              "Pias",
              "Poblacion",
              "Velasco"
            ],
            "Tineg": [
              "Poblacion",
              "Alaoa",
              "Anayan",
              "Apao",
              "Belaat",
              "Caganayan",
              "Cogon",
              "Lanec",
              "Lapat-Balantay",
              "Naglibacan"
            ],
            "Tubo": [
              "Alangtin",
              "Amtuagan",
              "Dilong",
              "Kili",
              "Poblacion",
              "Supo",
              "Tiempo",
              "Tubtuba",
              "Wayangan",
              "Tabacda"
            ],
            "Villaviciosa": [
              "Ap-apaya",
              "Bol-lilising",
              "Cal-lao",
              "Lap-lapog",
              "Lumaba",
              "Poblacion",
              "Tamac",
              "Tuquib"
            ]
          },
          "Benguet": {
            "Atok": [
              "Abiang",
              "Caliking",
              "Cattubo",
              "Naguey",
              "Paoay",
              "Pasdong",
              "Poblacion",
              "Topdac"
            ],
            "Bakun": [
              "Ampusongan",
              "Bagu",
              "Dalipey",
              "Gambang",
              "Kayapa",
              "Poblacion",
              "Sinacbat"
            ],
            "Bokod": [
              "Ambuclao",
              "Bila",
              "Bobok-Bisal",
              "Daclan",
              "Ekip",
              "Karao",
              "Nawal",
              "Pito",
              "Poblacion",
              "Tikey"
            ],
            "Buguias": [
              "Abatan",
              "Amgaleyguey",
              "Amlimay",
              "Baculongan Norte",
              "Bangao",
              "Buyacaoan",
              "Calamagan",
              "Catlubong",
              "Loo",
              "Natubleng",
              "Poblacion",
              "Baculongan Sur",
              "Lengaoan",
              "Sebang"
            ],
            "Itogon": [
              "Ampucao",
              "Dalupirip",
              "Gumatdang",
              "Loacan",
              "Poblacion",
              "Tinongdan",
              "Tuding",
              "Ucab",
              "Virac"
            ],
            "Kabayan": [
              "Adaoay",
              "Anchukey",
              "Ballay",
              "Bashoy",
              "Batan",
              "Duacan",
              "Eddet",
              "Gusaran",
              "Kabayan Barrio",
              "Lusod",
              "Pacso",
              "Poblacion",
              "Tawangan"
            ],
            "Kapangan": [
              "Balakbak",
              "Beleng-Belis",
              "Boklaoan",
              "Cayapes",
              "Cuba",
              "Datakan",
              "Gadang",
              "Gaswiling",
              "Labueg",
              "Paykek",
              "Poblacion Central",
              "Pudong",
              "Pongayan",
              "Sagubo",
              "Taba-ao"
            ],
            "Kibungan": [
              "Badeo",
              "Lubo",
              "Madaymen",
              "Palina",
              "Poblacion",
              "Sagpat",
              "Tacadang"
            ],
            "La Trinidad": [
              "Alapang",
              "Alno",
              "Ambiong",
              "Bahong",
              "Balili",
              "Beckel",
              "Bineng",
              "Betag",
              "Cruz",
              "Lubas",
              "Pico",
              "Poblacion",
              "Puguis",
              "Shilan",
              "Tawang",
              "Wangal"
            ],
            "Mankayan": [
              "Balili",
              "Bedbed",
              "Bulalacao",
              "Cabiten",
              "Colalo",
              "Guinaoang",
              "Paco",
              "Palasaan",
              "Poblacion",
              "Sapid",
              "Tabio",
              "Taneg"
            ],
            "Sablan": [
              "Bagong",
              "Balluay",
              "Banangan",
              "Banengbeng",
              "Bayabas",
              "Kamog",
              "Pappa",
              "Poblacion"
            ],
            "Tuba": [
              "Ansagan",
              "Camp One",
              "Camp 3",
              "Camp 4",
              "Nangalisan",
              "Poblacion",
              "San Pascual",
              "Tabaan Norte",
              "Tabaan Sur",
              "Tadiangan",
              "Taloy Norte",
              "Taloy Sur",
              "Twin Peaks"
            ],
            "Tublay": [
              "Ambassador",
              "Ambongdolan",
              "Ba-ayan",
              "Basil",
              "Daclan",
              "Caponga",
              "Tublay Central",
              "Tuel"
            ]
          },
          "Ifugao": {
            "Banaue": [
              "Amganad",
              "Anaba",
              "Bangaan",
              "Batad",
              "Bocos",
              "Banao",
              "Cambulo",
              "Ducligan",
              "Gohang",
              "Kinakin",
              "Poblacion",
              "Poitan",
              "San Fernando",
              "Balawis",
              "Ohaj",
              "Tam-an",
              "View Point",
              "Pula"
            ],
            "Hungduan": [
              "Abatan",
              "Bangbang",
              "Maggok",
              "Poblacion",
              "Bokiawan",
              "Hapao",
              "Lubo-ong",
              "Nungulunan",
              "Ba-ang"
            ],
            "Kiangan": [
              "Ambabag",
              "Baguinge",
              "Bokiawan",
              "Dalligan",
              "Duit",
              "Hucab",
              "Julongan",
              "Lingay",
              "Mungayang",
              "Nagacadan",
              "Pindongan",
              "Poblacion",
              "Tuplac",
              "Bolog"
            ],
            "Lagawe": [
              "Abinuan",
              "Banga",
              "Boliwong",
              "Burnay",
              "Buyabuyan",
              "Caba",
              "Cudog",
              "Dulao",
              "Jucbong",
              "Luta",
              "Montabiong",
              "Olilicon",
              "Poblacion South",
              "Ponghal",
              "Pullaan",
              "Tungngod",
              "Tupaya",
              "Poblacion East",
              "Poblacion North",
              "Poblacion West"
            ],
            "Lamut": [
              "Ambasa",
              "Hapid",
              "Lawig",
              "Lucban",
              "Mabatobato",
              "Magulon",
              "Nayon",
              "Panopdopan",
              "Payawan",
              "Pieza",
              "Poblacion East",
              "Pugol",
              "Salamague",
              "Bimpal",
              "Holowon",
              "Poblacion West",
              "Sanafe",
              "Umilag"
            ],
            "Mayoyao": [
              "Aduyongan",
              "Alimit",
              "Ayangan",
              "Balangbang",
              "Banao",
              "Banhal",
              "Bongan",
              "Buninan",
              "Chaya",
              "Chumang",
              "Guinihon",
              "Inwaloy",
              "Langayan",
              "Liwo",
              "Maga",
              "Magulon",
              "Mapawoy",
              "Mayoyao Proper",
              "Mongol",
              "Nalbu",
              "Nattum",
              "Palaad",
              "Poblacion",
              "Talboc",
              "Tulaed",
              "Bato-Alatbang",
              "Epeng"
            ],
            "Alfonso Lista": [
              "Bangar",
              "Busilac",
              "Calimag",
              "Calupaan",
              "Caragasan",
              "Dolowog",
              "Kiling",
              "Namnama",
              "Namillangan",
              "Pinto",
              "Poblacion",
              "San Jose",
              "San Juan",
              "San Marcos",
              "San Quintin",
              "Santa Maria",
              "Santo Domingo",
              "Little Tadian",
              "Ngileb",
              "Laya"
            ],
            "Aguinaldo": [
              "Awayan",
              "Bunhian",
              "Butac",
              "Chalalo",
              "Damag",
              "Galonogon",
              "Halag",
              "Itab",
              "Jacmal",
              "Majlong",
              "Mongayang",
              "Posnaan",
              "Ta-ang",
              "Talite",
              "Ubao",
              "Buwag"
            ],
            "Hingyon": [
              "Anao",
              "Bangtinon",
              "Bitu",
              "Cababuyan",
              "Mompolia",
              "Namulditan",
              "O-ong",
              "Piwong",
              "Poblacion",
              "Ubuag",
              "Umalbong",
              "Northern Cababuyan"
            ],
            "Tinoc": [
              "Ahin",
              "Ap-apid",
              "Binablayan",
              "Danggo",
              "Eheb",
              "Gumhang",
              "Impugong",
              "Luhong",
              "Tukucan",
              "Tulludan",
              "Wangwang"
            ],
            "Asipulo": [
              "Amduntog",
              "Antipolo",
              "Camandag",
              "Cawayan",
              "Hallap",
              "Namal",
              "Nungawa",
              "Panubtuban",
              "Pula",
              "Liwon"
            ]
          },
          "Kalinga": {
            "Balbalan": [
              "Ababa-an",
              "Balantoy",
              "Balbalan Proper",
              "Balbalasang",
              "Buaya",
              "Dao-angan",
              "Gawa-an",
              "Mabaca",
              "Maling",
              "Pantikian",
              "Poswoy",
              "Poblacion",
              "Talalang",
              "Tawang"
            ],
            "Lubuagan": [
              "Dangoy",
              "Mabilong",
              "Mabongtot",
              "Poblacion",
              "Tanglag",
              "Lower Uma",
              "Upper Uma",
              "Antonio Canao",
              "Uma del Norte"
            ],
            "Pasil": [
              "Ableg",
              "Balatoc",
              "Balinciagao Norte",
              "Cagaluan",
              "Colayo",
              "Dalupa",
              "Dangtalan",
              "Galdang",
              "Guina-ang",
              "Magsilay",
              "Malucsad",
              "Pugong",
              "Balenciagao Sur",
              "Bagtayan"
            ],
            "Pinukpuk": [
              "Aciga",
              "Allaguia",
              "Ammacian",
              "Apatan",
              "Ba-ay",
              "Ballayangon",
              "Bayao",
              "Wagud",
              "Camalog",
              "Katabbogan",
              "Dugpa",
              "Cawagayan",
              "Asibanglan",
              "Limos",
              "Magaogao",
              "Malagnat",
              "Mapaco",
              "Pakawit",
              "Pinukpuk Junction",
              "Socbot",
              "Taga",
              "Pinococ",
              "Taggay"
            ],
            "Rizal": [
              "Babalag East",
              "Calaocan",
              "Kinama",
              "Liwan East",
              "Liwan West",
              "Macutay",
              "San Pascual",
              "San Quintin",
              "Santor",
              "Babalag West",
              "Bulbol",
              "Romualdez",
              "San Francisco",
              "San Pedro"
            ],
            "City of Tabuk": [
              "Agbannawag",
              "Amlao",
              "Appas",
              "Bagumbayan",
              "Balawag",
              "Balong",
              "Bantay",
              "Bulanao",
              "Cabaritan",
              "Cabaruan",
              "Calaccad",
              "Calanan",
              "Dilag",
              "Dupag",
              "Gobgob",
              "Guilayon",
              "Lanna",
              "Laya East",
              "Laya West",
              "Lucog",
              "Magnao",
              "Magsaysay",
              "Malalao",
              "Masablang",
              "Nambaran",
              "Nambucayan",
              "Naneng",
              "Dagupan Centro",
              "San Juan",
              "Suyang",
              "Tuga",
              "Bado Dangwa",
              "Bulo",
              "Casigayan",
              "Cudal",
              "Dagupan Weste",
              "Lacnog",
              "Malin-awa",
              "New Tanglag",
              "San Julian",
              "Bulanao Norte",
              "Ipil",
              "Lacnog West"
            ],
            "Tanudan": [
              "Anggacan",
              "Babbanoy",
              "Dacalan",
              "Gaang",
              "Lower Mangali",
              "Lower Taloctoc",
              "Lower Lubo",
              "Upper Lubo",
              "Mabaca",
              "Pangol",
              "Poblacion",
              "Upper Taloctoc",
              "Anggacan Sur",
              "Dupligan",
              "Lay-asan",
              "Mangali Centro"
            ],
            "Tinglayan": [
              "Ambato Legleg",
              "Bangad Centro",
              "Basao",
              "Belong Manubal",
              "Butbut",
              "Bugnay",
              "Buscalan",
              "Dananao",
              "Loccong",
              "Luplupa",
              "Mallango",
              "Poblacion",
              "Sumadel 1",
              "Sumadel 2",
              "Tulgao East",
              "Tulgao West",
              "Upper Bangad",
              "Ngibat",
              "Old Tinglayan",
              "Lower Bangad"
            ]
          },
          "Mountain Province": {
            "Barlig": [
              "Chupac",
              "Fiangtin",
              "Kaleo",
              "Latang",
              "Lias Kanluran",
              "Lingoy",
              "Lunas",
              "Macalana",
              "Ogo-og",
              "Gawana",
              "Lias Silangan"
            ],
            "Bauko": [
              "Abatan",
              "Bagnen Oriente",
              "Bagnen Proper",
              "Balintaugan",
              "Banao",
              "Bila",
              "Guinzadan Central",
              "Guinzadan Norte",
              "Guinzadan Sur",
              "Lagawa",
              "Leseb",
              "Mabaay",
              "Mayag",
              "Monamon Norte",
              "Monamon Sur",
              "Mount Data",
              "Otucan Norte",
              "Otucan Sur",
              "Poblacion",
              "Sadsadan",
              "Sinto",
              "Tapapan"
            ],
            "Besao": [
              "Agawa",
              "Ambaguio",
              "Banguitan",
              "Besao East",
              "Besao West",
              "Catengan",
              "Gueday",
              "Lacmaan",
              "Laylaya",
              "Padangan",
              "Payeo",
              "Suquib",
              "Tamboan",
              "Kin-iway"
            ],
            "Bontoc": [
              "Alab Proper",
              "Alab Oriente",
              "Balili",
              "Bayyo",
              "Bontoc Ili",
              "Caneo",
              "Dalican",
              "Gonogon",
              "Guinaang",
              "Mainit",
              "Maligcong",
              "Samoki",
              "Talubin",
              "Tocucan",
              "Poblacion",
              "Caluttit"
            ],
            "Natonin": [
              "Alunogan",
              "Balangao",
              "Banao",
              "Banawal",
              "Butac",
              "Maducayan",
              "Poblacion",
              "Saliok",
              "Sta. Isabel",
              "Tonglayan",
              "Pudo"
            ],
            "Paracelis": [
              "Anonat",
              "Bacarri",
              "Bananao",
              "Bantay",
              "Butigue",
              "Bunot",
              "Buringal",
              "Palitud",
              "Poblacion"
            ],
            "Sabangan": [
              "Bao-angan",
              "Bun-ayan",
              "Busa",
              "Camatagan",
              "Capinitan",
              "Data",
              "Gayang",
              "Lagan",
              "Losad",
              "Namatec",
              "Napua",
              "Pingad",
              "Poblacion",
              "Supang",
              "Tambingan"
            ],
            "Sadanga": [
              "Anabel",
              "Belwang",
              "Betwagan",
              "Bekigan",
              "Poblacion",
              "Sacasacan",
              "Saclit",
              "Demang"
            ],
            "Sagada": [
              "Aguid",
              "Tetepan Sur",
              "Ambasing",
              "Angkeling",
              "Antadao",
              "Balugan",
              "Bangaan",
              "Dagdag",
              "Demang",
              "Fidelisan",
              "Kilong",
              "Madongo",
              "Poblacion",
              "Pide",
              "Nacagang",
              "Suyo",
              "Taccong",
              "Tanulong",
              "Tetepan Norte"
            ],
            "Tadian": [
              "Balaoa",
              "Banaao",
              "Bantey",
              "Batayan",
              "Bunga",
              "Cadad-anan",
              "Cagubatan",
              "Duagan",
              "Dacudac",
              "Kayan East",
              "Lenga",
              "Lubon",
              "Mabalite",
              "Masla",
              "Pandayan",
              "Poblacion",
              "Sumadel",
              "Tue",
              "Kayan West"
            ]
          },
          "Apayao": {
            "Calanasan": [
              "Butao",
              "Cadaclan",
              "Langnao",
              "Lubong",
              "Naguilian",
              "Namaltugan",
              "Poblacion",
              "Sabangan",
              "Santa Filomena",
              "Tubongan",
              "Tanglagan",
              "Tubang",
              "Don Roque Ablan Sr.",
              "Eleazar",
              "Eva Puzon",
              "Kabugawan",
              "Macalino",
              "Santa Elena"
            ],
            "Conner": [
              "Allangigan",
              "Buluan",
              "Caglayan",
              "Calafug",
              "Cupis",
              "Daga",
              "Guinamgaman",
              "Karikitan",
              "Katablangan",
              "Malama",
              "Manag",
              "Nabuangan",
              "Paddaoan",
              "Puguin",
              "Ripang",
              "Sacpil",
              "Talifugo",
              "Banban",
              "Guinaang",
              "Ili",
              "Mawigue"
            ],
            "Flora": [
              "Allig",
              "Anninipan",
              "Atok",
              "Bagutong",
              "Balasi",
              "Balluyan",
              "Malayugan",
              "Malubibit Norte",
              "Poblacion East",
              "Tamalunog",
              "Mallig",
              "Malubibit Sur",
              "Poblacion West",
              "San Jose",
              "Santa Maria",
              "Upper Atok"
            ],
            "Kabugao": [
              "Badduat",
              "Baliwanan",
              "Bulu",
              "Dagara",
              "Dibagat",
              "Cabetayan",
              "Karagawan",
              "Kumao",
              "Laco",
              "Lenneng",
              "Lucab",
              "Luttuacan",
              "Madatag",
              "Madduang",
              "Magabta",
              "Maragat",
              "Musimut",
              "Nagbabalayan",
              "Poblacion",
              "Tuyangan",
              "Waga"
            ],
            "Luna": [
              "Bacsay",
              "Capagaypayan",
              "Dagupan",
              "Lappa",
              "Marag",
              "Poblacion",
              "Quirino",
              "Salvacion",
              "San Francisco",
              "San Isidro Norte",
              "San Sebastian",
              "Santa Lina",
              "Tumog",
              "Zumigui",
              "Cagandungan",
              "Calabigan",
              "Cangisitan",
              "Luyon",
              "San Gregorio",
              "San Isidro Sur",
              "Shalom",
              "Turod"
            ],
            "Pudtol": [
              "Aga",
              "Alem",
              "Cabatacan",
              "Cacalaggan",
              "Capannikian",
              "Lower Maton",
              "Malibang",
              "Mataguisi",
              "Poblacion",
              "San Antonio",
              "Swan",
              "Upper Maton",
              "Amado",
              "Aurora",
              "Doña Loreta",
              "Emilia",
              "Imelda",
              "Lt. Balag",
              "Lydia",
              "San Jose",
              "San Luis",
              "San Mariano"
            ],
            "Santa Marcela": [
              "Barocboc",
              "Consuelo",
              "Imelda",
              "Malekkeg",
              "Marcela",
              "Nueva",
              "Panay",
              "San Antonio",
              "Sipa Proper",
              "Emiliana",
              "San Carlos",
              "San Juan",
              "San Mariano"
            ]
          },
          "City of Baguio": {
            "City of Baguio": [
              "Apugan-Loakan",
              "Asin Road",
              "Atok Trail",
              "Bakakeng Central",
              "Bakakeng North",
              "Happy Hollow",
              "Balsigan",
              "Bayan Park West",
              "Bayan Park East",
              "Brookspoint",
              "Brookside",
              "Cabinet Hill-Teacher's Camp",
              "Camp Allen",
              "Camp 7",
              "Camp 8",
              "Campo Filipino",
              "City Camp Central",
              "City Camp Proper",
              "Country Club Village",
              "Cresencia Village",
              "Dagsian, Upper",
              "DPS Area",
              "Dizon Subdivision",
              "Quirino Hill, East",
              "Engineers' Hill",
              "Fairview Village",
              "Fort del Pilar",
              "General Luna, Upper",
              "General Luna, Lower",
              "Gibraltar",
              "Greenwater Village",
              "Guisad Central",
              "Guisad Sorong",
              "Hillside",
              "Holy Ghost Extension",
              "Holy Ghost Proper",
              "Imelda Village",
              "Irisan",
              "Kayang Extension",
              "Kias",
              "Kagitingan",
              "Loakan Proper",
              "Lopez Jaena",
              "Lourdes Subdivision Extension",
              "Dagsian, Lower",
              "Lourdes Subdivision, Lower",
              "Quirino Hill, Lower",
              "General Emilio F. Aguinaldo",
              "Lualhati",
              "Lucnab",
              "Magsaysay, Lower",
              "Magsaysay Private Road",
              "Aurora Hill Proper",
              "Bal-Marcoville",
              "Quirino Hill, Middle",
              "Military Cut-off",
              "Mines View Park",
              "Modern Site, East",
              "Modern Site, West",
              "New Lucban",
              "Aurora Hill, North Central",
              "Sanitary Camp, North",
              "Outlook Drive",
              "Pacdal",
              "Pinget",
              "Pinsao Pilot Project",
              "Pinsao Proper",
              "Poliwes",
              "Pucsusan",
              "MRR-Queen Of Peace",
              "Rock Quarry, Lower",
              "Salud Mitra",
              "San Antonio Village",
              "San Luis Village",
              "San Roque Village",
              "San Vicente",
              "Santa Escolastica",
              "Santo Rosario",
              "Santo Tomas School Area",
              "Santo Tomas Proper",
              "Scout Barrio",
              "Session Road Area",
              "Slaughter House Area",
              "Sanitary Camp, South",
              "Saint Joseph Village",
              "Teodora Alonzo",
              "Trancoville",
              "Rock Quarry, Upper",
              "Victoria Village",
              "Quirino Hill, West",
              "Andres Bonifacio",
              "Legarda-Burnham-Kisad",
              "Imelda R. Marcos",
              "Lourdes Subdivision, Proper",
              "Quirino-Magsaysay, Upper",
              "A. Bonifacio-Caguioa-Rimando",
              "Ambiong",
              "Aurora Hill, South Central",
              "Abanao-Zandueta-Kayong-Chugum-Otek",
              "Bagong Lipunan",
              "BGH Compound",
              "Bayan Park Village",
              "Camdas Subdivision",
              "Palma-Urbano",
              "Dominican Hill-Mirador",
              "Alfonso Tabora",
              "Dontogan",
              "Ferdinand",
              "Happy Homes",
              "Harrison-Claudio Carantes",
              "Honeymoon",
              "Kabayanihan",
              "Kayang-Hilltop",
              "Gabriela Silang",
              "Liwanag-Loakan",
              "Malcolm Square-Perfecto",
              "Manuel A. Roxas",
              "Padre Burgos",
              "Quezon Hill, Upper",
              "Rock Quarry, Middle",
              "Phil-Am",
              "Quezon Hill Proper",
              "Middle Quezon Hill Subdivision",
              "Rizal Monument Area",
              "SLU-SVP Housing Village",
              "South Drive",
              "Magsaysay, Upper",
              "Market Subdivision, Upper",
              "Padre Zamora"
            ]
          }
        }
